openapi: "3.1.0"
info:
  title: PA Vietnam Support API
  version: "1.0.0"
  description: API cho hệ thống ticket hỗ trợ khách hàng
  contact:
    name: PA Vietnam
    email: dev@pavietnam.vn

servers:
  - url: https://apigateway.pavietnam.vn
    description: Production

tags:
  - name: Ticket
    description: Các API liên quan đến ticket hỗ trợ khách hàng

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

    basicAuth:
      type: http
      scheme: basic
paths:
  /v1/users/{user_id}/tickets:
    $ref: "./paths/tickets/create.yaml"
  /v1/users/{user_id}/tickets/{id}:
    $ref: "./paths/tickets/detail.yaml"
  /v1/users/{user_id}/tickets/{id}/close:
    $ref: "./paths/tickets/close.yaml"
  /v1/users/{user_id}/tickets/{id}/reopen:
    $ref: "./paths/tickets/reopen.yaml"
