name: Check API Differences

on:
  workflow_call:

jobs:
  diff:
    name: Check API Differences
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with: { path: new }
      - uses: actions/checkout@v4
        with: { ref: main, path: old }

      - name: Install oasdiff
        env:
          VERSION: 1.15.3
        run: |
          curl -fsSL https://github.com/oasdiff/oasdiff/releases/download/v${VERSION}/oasdiff_${VERSION}_linux_amd64.tar.gz | tar -xz
          sudo mv oasdiff /usr/local/bin/

      - name: Check API changelog
        run: oasdiff changelog old/openapi.yaml new/openapi.yaml || true

      # - name: Check breaking changes
      #   id: diff
      #   run: |
      #     oasdiff breaking old/openapi.yaml new/openapi.yaml > result.txt 2>&1 || true
      #     echo "output<<EOF" >> $GITHUB_OUTPUT
      #     cat result.txt >> $GITHUB_OUTPUT
      #     echo "EOF" >> $GITHUB_OUTPUT
      #     oasdiff breaking old/openapi.yaml new/openapi.yaml --format githubactions -o WARN
